My Portfolio Mobile Version Skeleton Microverse Project Complete
David-Kasilia/My-Portfolio-Mobile-Version-Skeleton-Microverse-Project pull request #2
Opened 2022-06-29 21:01 UTC by David-Kasilia

- After Merging the setup-project branch with the main branch I completed the following:
- Created the initialization-project branch to build the project code.
- Opened the folder Using VSCode.
- Completed the HTML code first
- Completed the CSS part.
- I tested the website by running the code to a live server and opened it with Mozilla Firefox.
- To ensure the Webpage was responsive and was in a mobile version skeleton I used the developer tools to see if it was responsive.

2022-06-29 22:20 UTC, MeqdamAlqudah requested changes
Hi @David-Kasilia , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
![](https://media1.giphy.com/media/l49JWMZfuyqbikTDi/200w.webp?cid=ecf05e47xyo354ncw5ah9fcikqeg4c116tiun3p0k4sv5cg0&rid=200w.webp&ct=g)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 22:20 UTC, MeqdamAlqudah commented on index.html
> +
- Please The section should have the margins (top, bottom, left, right) defined in the design

| Your Design | Figma design |
| ---------------- | ------------------ |
| ![image](https://user-images.githubusercontent.com/74744787/176552643-6bd65c81-ec91-4bb6-97e7-b6080368f486.png) | ![image](https://user-images.githubusercontent.com/74744787/176552745-19dce0aa-8f16-49f5-b00a-195bc5546a8c.png) |

2022-06-29 22:20 UTC, MeqdamAlqudah commented on index.html
> +    <img class="line" src="./images/line-1.png" alt="Horizontal line">
- [ ] Please fix the margin and the padding of the website 
![image](https://user-images.githubusercontent.com/74744787/176555086-45f6d0ca-313a-47ea-a046-f05ff60b1e92.png)

2022-06-30 08:23 UTC, topeogunleye approved these changes
### Hi @David-Kasilia, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- PR has a good description summary :heavy_check_mark:
 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 09:12 UTC, merged